name: publish
on:
  push:
    branches:
      - master
jobs:
  build-sdk:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn test
      - run: yarn build

  deploy:
    needs: build-sdk
    runs-on: [ubuntu-latest]
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
